### ISSUE TITLE
Wrong editing language 

### ISSUE THREAD

**Issue by LambdAurora** [TsundereBug/discord-intellij#13]
I was working with CLion and when I looked at Discord it says that I'm editing an Objective-C file but it's a C++ file!

Discord Rich Presence:
![image](https://user-images.githubusercontent.com/12587332/34414316-efa0fff2-ebe8-11e7-8e08-cbc3e64c1fb1.png)
CLion:
![image](https://user-images.githubusercontent.com/12587332/34414346-200c803a-ebe9-11e7-977d-f0712636fe31.png)

**Comment by s5bug** [comment]
That is really weird.

The way I handle my file<>icon management is by getting the file type and showing that, so this is probably a bug with CLion.

Can you reproduce on _all_ C++ files?

**Comment by notmeta** [comment]
I have this too, I've only just installed CLion.

**Comment by s5bug** [comment]
CLion bug then. Will check it out on my own install and open a bug report.

**Comment by s5bug** [comment]
Can you still reproduce this on the latest (including EAP) version of CLion?

**Comment by LambdAurora** [comment]
Yep, I can still reproduce this on the latest version (EAP) of CLion.

Discord Rich Presence:
![Discord Rich Presence Image 1](https://user-images.githubusercontent.com/12587332/35937060-52d447e2-0c45-11e8-8c73-c332b70cb04f.png)
![Discord Rich Presence Image 2](https://puu.sh/ziMec/b1dafd58c2.png)
CLion:
![CLion image](https://puu.sh/ziLN0/085b303d39.png)

**Comment by miawgogo** [comment]
I am also getting the same issue with C files 
![image](https://user-images.githubusercontent.com/7449028/36158301-e40b7432-10d3-11e8-9fe4-ee080e2e9767.png)

**Comment by s5bug** [comment]
Alright. I'll file a bug on CLion in about an hour.

**Comment by s5bug** [comment]
I forgot to file a bug report 🤦‍♂️ will open one right now :/

**Comment by s5bug** [comment]
https://youtrack.jetbrains.com/issue/CPP-12320 Will reopen if JetBrains says they solved and there are still issues with C and C++ files.
