### ISSUE TITLE
Time counter doesn't show days

### ISSUE THREAD

**Issue by alesharik** [TsundereBug/discord-intellij#14]
After 23:59:59 Discord showed 00:00 instead of 1:00:00:00

**Comment by Almighty-Alpaca** [comment]
This is a known issue in the desktop client of Discord and thus can't be fixed by the plugin itself.

You can track the issue on [Discord's Trello board here](https://trello.com/c/j6sAR8Ty/).

**Comment by s5bug** [comment]
(And honestly if you've been in a project for over 24 hours you might need to just take a break)
