### ISSUE TITLE
Incompatible with Android Studio 3.0.1

### ISSUE THREAD

**Issue by G0BL1N** [TsundereBug/discord-intellij#15]
![image](https://user-images.githubusercontent.com/18249498/35046988-a654c36c-fba9-11e7-8f01-429167612946.png)

**Comment by s5bug** [comment]
Are you on the latest version of AS?

**Comment by G0BL1N** [comment]
Yes, I am on the latest version.

**Comment by s5bug** [comment]
Can you make a paste/haste/gist of the log?

**Comment by G0BL1N** [comment]
https://gist.github.com/G0BL1N/08192630b292f9d0a593f901cd9527bf
Doesn't seems to reflect me trying to install plugin though. But IDE build version is visible, which is 171 (and this is 100% the latest version) , and your plugin minimal version is 175 according to plugin.xml.

**Comment by s5bug** [comment]
Android Studio requires an update before this plugin will work.

In the mean time, use IntelliJ Community with the Android plugin as it's basically the same thing 👍 

The plugin is compatible with 172+ :)

**Comment by s5bug** [comment]
Locked as #16 being a clearer and discussable issue.
