### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by IamTails** [TsundereBug/discord-intellij#16]
"Plugin 'IntelliJ Discord Integration' is incompatible with this installation"
unable to install on 
Android Studio 3.0.1
Build #AI-171.4443003, built on November 9, 2017
JRE: 1.8.0_152-release-915-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by G0BL1N** [comment]
This is the same problem i had (#15), and it looks like AS Stable version is a little bit too low for this plugin. Solution suggested by the @TsundereBug was to install Intellij IDEA instead of AS, but i decided to try Android Studio Canary. And plugin worked, **except** for the icon in Discord, which is really sad(and i should probably open another issue for that). 
To put it simple, this plugin currently doesn't fully support Android Studio, nor Canary nor Stable.

**Comment by s5bug** [comment]
Closing #15 due to this issue being better documented.

@G0BL1N The icon doesn't work due to me not having it added in the RPC settings. Can you post a screenshot of the Build Number dialog under Help -> About?

**Comment by IamTails** [comment]
I use IntelliJ as well but I find the Android plug-in for it to be unstable so I stick to as for my apps

**Comment by s5bug** [comment]
Hopefully AS is updated soon and I can update the icon and get it working.

**Comment by G0BL1N** [comment]
> @G0BL1N The icon doesn't work due to me not having it added in the RPC settings.

Thats what i thought :)
Here:
```
Android Studio 3.1 Canary 9
Build #AI-173.4559767, built on January 23, 2018
JRE: 1.8.0_152-release-1024-b02 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by s5bug** [comment]
Is the build number `#AI-xxx` on Stable as well? Or `#AS` like I previously believed.

**Comment by G0BL1N** [comment]
It is `#AI-xxx` on Stable too, whatever `AI` means...

**Comment by s5bug** [comment]
Probably `Android IDE`. I'll add the icon later.

**Comment by s5bug** [comment]
I can't find an Android Studio icon in the Press Kit, so as of now I'm closing this. If someone can find the official downloads from AS Press Kit, I'll reopen.

**Comment by IamTails** [comment]
https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Android_Studio_icon.svg/2000px-Android_Studio_icon.svg.png best I could find

**Comment by IamTails** [comment]
Here this is 1024x1024 which is what I think is this size needed for Rich present 
![androidstudio](https://user-images.githubusercontent.com/21271709/35844396-3fab1468-0adb-11e8-8ef6-e9cd14040a9b.png)
