### ISSUE TITLE
No icons for appcode or swift

### ISSUE THREAD

**Issue by IamTails** [TsundereBug/discord-intellij#17]
Everything else functions fine other then the lack of icons 
Ver:
#OC-173.4591.3

**Comment by s5bug** [comment]
Swift should have an icon. Can you post a screenshot of your rich presence
while editing a swift file?

**Comment by IamTails** [comment]
![screen shot 2018-02-05 at 2 00 06 am](https://user-images.githubusercontent.com/21271709/35791941-5c2d9bf6-0a18-11e8-875f-96f5f835d212.png)

**Comment by s5bug** [comment]
Alright. An icon should be up for AppCode within a few days. 😁

**Comment by IamTails** [comment]
thanks buddy

**Comment by s5bug** [comment]
AppCode added :)
