### ISSUE TITLE
Plugins received an unexpected RPC error

### ISSUE THREAD

**Issue by Dwood15** [TsundereBug/discord-intellij#19]
The plugin has received an unexpected RPC error.
       Code: 4000 / child "activity" fails because [child "assets" fails because [child "large_text" fails because ["large_text" length must be at least 2 characters long]]]

This _looks_ like it was a one-time error, so I'm starting the issue closed, but just in case someone else encounters the same thing, this can be here.

**Comment by s5bug** [comment]
This happens when your filename is one character.

EDIT: no, there should be no reason that this happens. Huh.

**Comment by Dwood15** [comment]
Ruh-Roh, happened again today at startup of CLion 

5:56 PM	Plugins received an unexpected RPC error
				The plugin has received an unexpected RPC error.
				Code: 4000 / child "activity" fails because [child "assets" fails because [child "large_text" fails because ["large_text" length must be at least 2 characters long]]]

More details: 

OS: x64 Windows 7. 
CPU: intel core i5-4690, 
32 GB ram
![clion_latest](https://user-images.githubusercontent.com/8879021/38003573-51c3d266-31f5-11e8-82ad-b940541557d7.png)

**Comment by Dwood15** [comment]
Restarting CLion and the error does not reoccur.

Edit: For now, the inconvenience is so minor I really don't care that much, but if I find out the source of the issue, will let you know.

**Comment by s5bug** [comment]
I don't see why this could be, unless...

The startup might open to a C file, which has an ID of 1 character. Can you
confirm that this happens when you switch to C files?

Dason Woodhouse <notifications@github.com> schrieb am Di., 27. März 2018,
18:32:

**Comment by Dwood15** [comment]
I've enabled debug mode, so if it occurs again I'll post up the details.  I often use *.h files, but I don't have a single 1-character filename in my actual project, unless some get generated by cmake? 

Testing now, will edit//post back with details.

**Comment by Dwood15** [comment]
Here's an exception log.

[CL-2018-03-30_21-22-58.zip](https://github.com/TsundereBug/discord-intellij/files/1865159/CL-2018-03-30_21-22-58.zip)

It happens in other projects as well...

**Comment by s5bug** [comment]
Your errors don't come from my plugin. If you'd like to use mine, follow these instructions:

- Go to File->Settings
- Click on "Plugins" in the left menu
- Search for "Discord Integration" in your plugins
- Uninstall it
- Do not restart yet
- Click the "Browse Repositories" button
- Search for "IntelliJ Discord Integration"
- Install the one that says "IntelliJ Discord Integration" and not "Discord Integration"
- Reboot

**Comment by Dwood15** [comment]
Ah, my apologies.
