### ISSUE TITLE
Does this work on Ubuntu?

### ISSUE THREAD

**Issue by Azure-Agst** [TsundereBug/discord-intellij#20]
Sorry for the super generic sounding question, but I can't seem to get this to work at all on Ubuntu 16.04. After fumbling around with the package and even testing some of it's older versions, I couldn't get it to function; I could enable the package, but I would see no results. Even the logs say that the plugin launches fine:

```
2018-03-26 20:17:58,259 [   3456]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: IntelliJ Discord Integration (2.0), Markdown support (173.4301.21), Material Theme UI (1.6.1) 
```

If it's worth anything, I'm using CLion (build #CL-173.4674.29, 05 Mar 2018 11:41) installed via snap.

Thanks!

**Comment by s5bug** [comment]
Once the plugin is installed, reload discord. Once discord finishes its
reload, in CLion, File -> Restart -> Restart and Invalidate. Should work
after that.

**Comment by Azure-Agst** [comment]
@TsundereBug Hmm, nope. Tried doing as you said and still nothing. Tried doing a hard reboot as well and that also did nothing. Tried updating to Vaatu's most recent release of discord-rpc.jar and nevertheless the problem persisted.

I'm not a java developer (as you can tell by the IDE I'm using) but I've forked the repo and I'll see if I can debug it to figure out what exactly's going wrong.

**Comment by Azure-Agst** [comment]
hm. tried it on my windows 64bit machine and it still doesn't work. tried the invalidation trick and still nothing. :/

**Comment by s5bug** [comment]
Don't have intellij as a game in discord and allow it to find games
automatically? I don't know what else to say besides that.

just call me azure <notifications@github.com> schrieb am Di., 27. März
2018, 05:06:

**Comment by revsuine** [comment]
Just thought I'd say I'm having the same issue on vanilla Ubuntu 16.04. I don't code on my Windows machine but I can try it just in case. Tried with both IntelliJ and PyCharm. IntelliJ and PyCharm were installed from the Ubuntu store, and Discord from the official website.

Edit: FWIW, I manually added PyCharm as a game (still no rich presence though). Also, PyCharm is installed at `/snap/pycharm-community/58/jre64/bin` (`./java` is the executable) and Discord is in `/usr/bin/discord`.

**Comment by s5bug** [comment]
Can you get me any logs?

**Comment by revsuine** [comment]
Sure. [This](https://hastebin.com/kiralaqevi.rb) should be my startup log for the current session, I believe? Let me know if you want more of it, wasn't sure how much to send.

**Comment by s5bug** [comment]
I don't remember how to grab the log file, but the entire log file will
work.

**Comment by revsuine** [comment]
@TsundereBug I only gave a partial log because all the paste sites I could find didn't allow files of that size, but I believe [this](https://gist.github.com/paradoor/dbf25f079ecf09d9e48a6ecb2451fd31) gist should work.

**Comment by s5bug** [comment]
I can't figure out for the life of me why the plug-in doesn't work. Can you
try updating to version 2.2 in the plugins menu?

**Comment by revsuine** [comment]
Have updated to 2.2. Discord still isn't detecting anything. Sorry :/ If there's anything I can do to give more info, I'd be happy to do so

**Comment by s5bug** [comment]
@Vatuu I'm out of ideas. Got anything?

**Comment by Azure-Agst** [comment]
Can confirm that it’s not just ubuntu not allowing Rich Presence, this Node.JS library worked when I tested it. (See [discord.js/RPC](https://github.com/discordjs/RPC).) @paradoor could you confirm any form of rich presence like this works while on ubuntu?

**Comment by revsuine** [comment]
@Azure-Agst Haven't tried that lib in specific, but I've tried a RPC plugin for VS Code and it worked. So it's probably something to do with the RPC lib this plugin is using. I actually tried another RPC JetBrains plugin and it didn't work either, so maybe it's something with Java or JetBrains IDEs?

**Comment by s5bug** [comment]
@paradoor @Azure-Agst Update to 2.2.1 given the zip in #18 and see if that fixes it

**Comment by Azure-Agst** [comment]
Seems to fix it. Thanks for the help!

**Comment by revsuine** [comment]
@TsundereBug Installed the zip and nothing happened. I could click the toggle button from the dropdown but Discord did not show anything. [Here](https://pastebin.com/PrNRGGbk) are the logs. As OP's problem is now fixed, I can start a new issue for this if you want?

**Comment by s5bug** [comment]
You made sure to not have the IDE listed in discord as a game, restarted
Discord, and then restarted the IDE?

**Comment by Vatuu** [comment]
Does everything work now?

**Comment by revsuine** [comment]
Yep, restarted both, and haven't listed anything as a game in Discord.

**Comment by s5bug** [comment]
Yeah, go ahead and set a new issue
