### ISSUE TITLE
 RTC connecting stuck - `~/null/discord-rpc.jar/discord-rpc.so`

### ISSUE THREAD

**Issue by petrleocompel** [TsundereBug/discord-intellij#23]
I'm using this plugin for some time and now i discovered I'm getting stuck when I'm connecting to voice channels. 

After few experiments i discovered file `~/null/discord-rpc.jar/discord-rpc.so` I dont know why its there but until this file exist I'm stucked at RTC connecting. After deleting file everything is back to normal. 
Maybe it's issue related to `discord-rpc.jar` and [discordrpc-jar/discord-rpc](https://github.com/discordrpc-jar/discord-rpc). 

Just now i have to delete this file everytime i want to start using Discordapp.

**Comment by s5bug** [comment]
That's not the library I use. Maybe check what is creating that file?

**Comment by s5bug** [comment]
![image](https://user-images.githubusercontent.com/7751296/38963817-95d5f04e-4328-11e8-8f3f-3ea0d8c488ff.png)

Update, see what's creating that jar, and I'll reopen if it's me
