### ISSUE TITLE
Android Studio problems. (No Image)

### ISSUE THREAD

**Issue by OhhLoz** [TsundereBug/discord-intellij#27]
I really like this plugin, the images look really nice and clean, the statuses update frequently and the app works well.   
However, when I try this using Android Studio I get no picture at all, even when editing supported file types (Java/XML). This is shown here: https://i.imgur.com/KUYiOAO.png  
I would love it if this could be fixed as this plugin works perfectly in IntelliJ IDEA (haven't tried it in other IDE's)

**Comment by s5bug** [comment]
There's no press icon for Android Studio. Send a screenshot of your Help ->
About so I can see build info?

**Comment by OhhLoz** [comment]
Yea sure its https://i.imgur.com/PVPd78h.png.  
I'm not quite sure what you mean about having no press icon, since Android Studio was based on IntelliJ wouldn't they function similarly or was this a design choice?

**Comment by s5bug** [comment]
The JetBrains presskit doesn't contain an official Android Studio icon. I also can't seem to find a high quality one on the AS webpage either.

**Comment by OhhLoz** [comment]
Does it need to be on a certain page or contained within the presskit? Or can it be from a webpage since there is a 2000x2000px version on wikipedia here https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Android_Studio_icon.svg/2000px-Android_Studio_icon.svg.png

**Comment by s5bug** [comment]
I was previously hesitant due to the fack that it didn't follow the style of the other icons, but I'll add it now until I am able to flesh out a unified icon set.
