### ISSUE TITLE
No Images

### ISSUE THREAD

**Issue by synfyi** [TsundereBug/discord-intellij#3]
Hi,

I just started using this and there are no icons for the program or the file I'm editing. There are for others but not me.

Please help!

**Comment by s5bug** [comment]
@x-Josh If there are no icons that either means:

1. You are using an unsupported IDE
2. You are using an unsupported language

Can you post screenshots of **your build number** (found in the IJ menu at Help->About) and **the RPC when you're editing a file** (found when clicking on your profile)?

**Comment by notmeta** [comment]
Hi, I get the same issue.
![IDE](https://vgy.me/bajfSz.png)
![RPC](https://vgy.me/Boh9fe.png)


**Update**:
Seems to be working now, but it doesn't work right away.

Suggestion: 
Would be nice if this could say something like "Playing IntelliJ IDEA" instead 

![status](https://vgy.me/BxODaX.png)

**Comment by s5bug** [comment]
@notmeta it used to say IntelliJ IDEA, but I was requested to change the name as it works for all JetBrains IDEs. People can see which you're using via the smaller icon.

Icons won't show right away as you need to change/open a file for the FileChange event to fire.

**Comment by notmeta** [comment]
@TsundereBug I mean it could be dynamic, it could say whichever IDE you're using at the time, not **just** 'IntelliJ IDEA'.

**Comment by s5bug** [comment]
@notmeta That's impossible via the RPC API :( If I was able to choose the playing status name I would. (I already have code set up for it)

**Comment by notmeta** [comment]
@TsundereBug god damn... shame

**Comment by s5bug** [comment]
Seems like this has been resolved or at least understood.
