### ISSUE TITLE
The ability to hide certain projects?

### ISSUE THREAD

**Issue by camdenorrb** [TsundereBug/discord-intellij#4]
I work on a couple of projects that are a sort of surprise, it would be nice if I can just disable the rich presence for said projects. Is this applicable?

**Comment by s5bug** [comment]
This is planned, but I don't know how to implement it.

**Comment by camdenorrb** [comment]
If I feel like messing with Scala and Intellij soon, I’ll try to help. But Scala is kinda foreign to me currently. I mainly do Kotlin and Java

**Comment by s5bug** [comment]
I don't mind configuration being written in Java :) What's your plan on implementation?

**Comment by camdenorrb** [comment]
Idk yet, I’ll have to look into it later, if you have a Discord or something we can talk personally about it after school.

**Comment by s5bug** [comment]
TsundereBug#0641

**Comment by s5bug** [comment]
Implementation idea:
* Create a button in the toolbar
* Have it change a config value on whether to show RPC or not

**Comment by s5bug** [comment]
I have a button style and layout planned. Cannot currently work on it, but I will get it done ASAP.

**Comment by s5bug** [comment]
oh yeah this is done now
