### ISSUE TITLE
Doesn't seem to work on PHPStorm

### ISSUE THREAD

**Issue by andre-paulo98** [TsundereBug/discord-intellij#5]
Tried using this plugin on PHPStorm and this is what i got:
![Result](https://i.imgur.com/pXPLQiK.png)

(btw i would recommend somewhere remember the user to activate the "Display playing game" option)

**Comment by s5bug** [comment]
It's working, you just haven't selected a file yet.

**Comment by andre-paulo98** [comment]
![selected files](https://i.imgur.com/7ZURmE9.png)
I do have multiple files open

**Comment by andre-paulo98** [comment]
nvm saw on #3 "Icons won't show right away as you need to change/open a file for the FileChange event to fire."
