### ISSUE TITLE
Dynamic application name for each Jetbrains product

### ISSUE THREAD

**Issue by judge2020** [TsundereBug/discord-intellij#8]
A nice enhancement would be to dynamically set the Application ID based on what IDEA program they're using, eg for PyCharm, it would show "Pycharm" name in discord and the pycharm logo instead of IntelliJ logo.

This can be achieved via creating multiple applications in the discord "my applications" panel, then conditionally setting the application ID based on what JetBrains product the plugin is running in. I haven't worked on IDEA plugins before so I'm not sure how to get the current product.

**Comment by s5bug** [comment]
1. Not splitting due to compatibility and future Discord features
2. It does show the IDE logo
3. Changing the name is impossible via RPC

**Comment by judge2020** [comment]
Multiple discord applications would be the only (hacky) way to get the name to change via RPC, however, I  understand why you'd like to keep it on a single app id.
